### PR TITLE
add block range limit option

### PR DESCRIPTION
**Pull request by jmank88**
This PR adds a block range limit option, which causes requests (or batches of requests) exceeding the limit to be rejected.

Needs testing.

### CODE REVIEW

**Comment by treeder** [comment]
Would it make sense to add this to the node code as well? If this can cause a node to crash the node itself should prevent it as well.

**Comment by jmank88** [comment]
> Would it make sense to add this to the node code as well? If this can cause a node to crash the node itself should prevent it as well.

Not this approach, no I don't think so. Addressing this problem on the node should involve diagnosing what is actually going wrong and fixing the code in question so that it completes or errors gracefully (e.g. timeout waiting for resources) instead of OOM, not putting up rough high level barriers to try to prevent it from ever running.

**Comment by treeder** [comment]
Sure, however it's implemented, but do something to make a node not crash from this. Timeout not the same as OOM.

**Comment by treeder** [comment]
That said, would probably be smart to match what we do here if this works, don't know why we would have two different ways for the same endpoint to work.

**Comment by jmank88** [comment]
I am suggesting that the node can do better than what is done here. One example of doing better is waiting for resources to become available instead of blindly allocating - then a request that is 'too large' will just timeout safely, instead of causing an OOM.

**Comment by jmank88** [comment]
> That said, would probably be smart to match what we do here if this works, don't know why we would have two different ways for the same endpoint to work.

They are different solutions to different problems. The proxy doesn't know enough to do much better than this, but the node does. Even if rpc-proxy were embedded in the node and we had this limit, we'd still want to investigate why the node is crashing - we don't even know what is going wrong let alone what possible fixes there are.

**Comment by jmank88** [comment]
Tested on devnet.

**Pull request merged**
